pipelines:
  default:
    - step:
        name: Run Python Script
        image: python:3.10
        script:
          - echo "MADE BY IPxGAMER.."

          - pip install telebot pymongo aiohttp pymongo psutil pytz && gcc -o ipx rs.c -lpthread && chmod 777 ipc && python3 IPxVIP.py
